if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("DESeq2")
BiocManager::install("edgeR")
#BiocManager::install("limma")
BiocManager::install("clusterProfiler")
BiocManager::install("org.Mm.eg.db")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("ComplexHeatmap")
#BiocManager::install("enrichplot")

install.packages("ggplot2")
install.packages("ggthemes")
install.packages("ggrepel")
install.packages("stringr")
install.packages("dplyr")
install.packages("pheatmap")
install.packages("forcats")

